### PR TITLE
Adds Bert prefixes

### PR DESCRIPTION
**Pull request by lordofthejars**
I created this PR  with some changes to adapt the Bert model when properties are prefixed with `bert`.

I tried to write some unit tests with Mockito, but I got crazy with JDK incompatibility problems with ByeBuddy, so the code is not complicated.

Even though this change supports Bert classification models, I don't know if it is enough. I saw that the model has some classification tensors, too, but I wonder if they need to be configured.

In any case, here is the PR we talked in https://github.com/tjake/Jlama/discussions/55

### CODE REVIEW

**Comment by tjake** [comment]
Great thanks for this, I like the approach.  I'll test it out and add a loadModelForEmbedding method

**Comment by lordofthejars** [comment]
Nice to see more code on this. Do you want I try on the Bert classification model to see if it works, or still some work needs to be done.

**Comment by tjake** [comment]
I verified it works with your model, but I think the classifier is used to say if a sentence is jailbreak or benign.  I'm guessing that can be done outside of jlama itself?

**Comment by tjake** [comment]
So technically that's a classifier vs an embedding though the embedding is used for classification.  I can add classification support but I need to add that as a Generation type etc.  I would say outside the scope of this specific PR

**Comment by lordofthejars** [comment]
Ok, so you mean that if I use the `loadEmbeddedModel` method, then it works, right? For now it is more than perfect :)

**Comment by tjake** [comment]
Yeah If  I put your model in I get:

```
Similarity between 'A man is eating food.' and 'A man is eating a piece of bread.' is 0.97 
Similarity between 'A man is eating food.' and 'The girl is carrying a baby.' is 0.79 
Similarity between 'A man is eating food.' and 'A man is riding a horse.' is 0.97 
Similarity between 'A man is eating food.' and 'A woman is playing violin.' is 0.96 
Similarity between 'A man is eating food.' and 'Two men pushed carts through the woods.' is 0.69 
Similarity between 'A man is eating food.' and 'A man is riding a white horse on an enclosed ground.' is 0.92 
Similarity between 'A man is eating food.' and 'A monkey is playing drums.' is 0.95 
Similarity between 'A man is eating food.' and 'Someone in a gorilla costume is playing a set of drums.' is 0.68 


Best match for: 'A man is eating food.' is 'A man is riding a horse.' ~ 0.97 
```

**Comment by lordofthejars** [comment]
Ok, but the model is to classify if it is benign or not, hummm

**Comment by tjake** [comment]
Yes the classifier is the thing you do after the embedding

**Comment by tjake** [comment]
Let me try adding the code you'd need here.

**Pull request merged**
